# 서버 포트설정
server:
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel.enabled: true
#    path: '/error'

# 로깅 추가
logging:
  pattern:
    console: "%d %-5level %logger %n %msg %n"
    file: "%d %-5level %logger %n %msg %n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.mycom: DEBUG

# 스프링 배너 제거
spring.main.banner-mode: "off"
spring.session.store-type: jdbc
spring:
  profiles:
    active: stg
    include: oauth, stgdb
  devtools:
    livereload:
      enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

---
server.port: 8080
spring.profiles: dev
spring.include: oauth, devdb

logging.file: logs/application-debug.log
logging.level.org.hibernate.type.descriptor.sql: trace

---
server.port: 8080
spring.profiles: stg
spring.include: oauth, stgdb

logging.file: /home/ec2-user/app/step1/logs/application-debug.log
logging.level.org.hibernate.type.descriptor.sql: trace

---
server.port: 8080
spring.profiles: real
spring.include: oauth, realdb

logging.file: /home/ec2-user/app/step1/logs/application-debug.log
logging.level.org.hibernate.type.descriptor.sql: info
