# 서버 포트설정
server:
  port: 8080

# 로깅 추가
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger %n %msg %n"
    file: "%d %-5level %logger %n %msg %n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.mycom: DEBUG

# 스프링 배너 제거
spring:
  profiles:
    active: dev
    include: oauth, devdb
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mustache:
    suffix: .mustache
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true

---
server:
  port: 8080
spring:
  profiles: dev
  include: oauth, devdb
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  session:
    store-type: jdbc

logging.level.org.hibernate.type.descriptor.sql: trace

---
spring:
  profiles: real
  incluse: oauth, realdb
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  session:
    store-type: jdbc

logging.level.org.hibernate.type.descriptor.sql: info