spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cdq7whhkkimw.ap-northeast-2.rds.amazonaws.com:3306/autumnia_db
    username: autumnia
    password: rlagoems00!