spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 501805108607-sda78lbvph96ruvdfq7tm9plqi6t3e16.apps.googleusercontent.com
            client-secret: M4j1z4V3ZeIsowMzo8PsnAI9
            scope: profile, email
          naver:
            client-id: jBrCNiGbDX3FeSzgzZ_o
            client-secret: gua2m0LzJ3
            redirect-url: {baseUrl}/{action}/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri=https: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me:
            user-name-attribute: response
