# 서버 포트설정
server:
  port: 80

# 로깅 추가
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger %n %msg %n"
    file: "%d %-5level %logger %n %msg %n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.mycom: DEBUG
    #org.hibernate: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


# 스프링 배너 제거
spring:
  profiles:
    active: local
#    include: oauth
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mustache:
    suffix: .mustache
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true

# registration
#  spring.security.oauth2.client.registration.naver.client-id=네이버클라이언트ID
#  spring.security.oauth2.client.registration.naver.client-secret=네이버클라이언트시크릿
#  spring.security.oauth2.client.registration.naver.redirect-uri={baseUrl}/{action}/oauth2/code/{registrationId}
#  spring.security.oauth2.client.registration.naver.authorization-grant-type=authorization_code
#  spring.security.oauth2.client.registration.naver.scope=name,email,profile_image
#  spring.security.oauth2.client.registration.naver.client-name=Naver

  # provider
#  spring.security.oauth2.client.provider.naver.authorization-uri=https://nid.naver.com/oauth2.0/authorize
#  spring.security.oauth2.client.provider.naver.token-uri=https://nid.naver.com/oauth2.0/token
#  spring.security.oauth2.client.provider.naver.user-info-uri=https://openapi.naver.com/v1/nid/me
#  spring.security.oauth2.client.provider.naver.user-name-attribute=response

---
spring:
  profiles: local
  h2:
    console:
      enabled: true

  jpa:
#    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  session:
    store-type: jdbc


---
spring:
  profiles: dev
#  datasource:
#    hikari:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      username: root
#      password: rlarkdmf00!
#      #connection-test-query: SELECT 1
#  thymeleaf:
#    cache: false
#  resources:
#    cache:
#      period: 0

---
spring:
  profiles: real
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/insight?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      username: root
#      password: rlarkdmf00!