server:
  port: 80

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

spring:
  main:
    banner-mode: "off"

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  spring:
    session:
      store-type: jdbc


#logging:
#  config: classpath:logback-${spring.profiles.active}.xml

---
#spring:
#  profiles: local
#    hikari:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      username: root
#      password: rlarkdmf00!
#      #connection-test-query: SELECT 1

#  datasource:
#    hikari:
#      allow-pool-suspension: true
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    hibernate:
#      use-new-id-generator-mappings: false

---
#spring:
#  profiles: dev
#  datasource:
#    hikari:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      username: root
#      password: rlarkdmf00!
#      #connection-test-query: SELECT 1
#  thymeleaf:
#    cache: false
#  resources:
#    cache:
#      period: 0

---
#spring:
#  profiles: real
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/insight?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      username: root
#      password: rlarkdmf00!